name: ltwcp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-406.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6

dev_dependencies:
  flutter_test: 
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
  fonts:
    - family: LS
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf
          weight: 700
    - family: JS
      fonts:
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-Medium.ttf
          weight: 300



